export { default as Navbar } from './Navbar/Navbar'
export { default as Header } from './Header/Header';
export { default as Hero } from './Hero/Hero';
export { default as About_Me } from './About_Me/About_Me';
export { default as Services } from './Services/Services';
export { default as Method } from './Method/Method';
export { default as Pricing } from './Pricing/Pricing';
export { default as Projects } from './Projects/Projects';
export { default as CTA } from './CTA/CTA';
export { default as Footer } from './Footer/Footer'